### ISSUE TITLE
Make 0.0.1 release

### ISSUE THREAD

**Issue by michaelweiser** [rgevaert/puppet-saslauthd#1]
Hi Rudy,

I'd like to package your module for Debian. For simplicity's sake, can you tag a 0.0.1 release so I can reference an upstream tarball from the package?

Thanks!
Michael

**Comment by rgevaert** [comment]
Hi Michel,

Sure no problem. I'm currently abroad and can't do that right now.  I will actually go through the code and make it follow the puppet style guide more.  I will do that shortly.

**Comment by rgevaert** [comment]
Hi Michel,

I did it now.  There is also a newer release with redhat support.
