### ISSUE TITLE
New Forge release

### ISSUE THREAD

**Issue by coreone** [rgevaert/puppet-saslauthd#5]
Don't want to be a pain, but since the PR I put in fixes a compilation bug, can you release a new version to the Forge so that we can start using a Forge release instead of a commit from the repo?

Thanks again for the amazing speed on that PR!

**Comment by rgevaert** [comment]
Sure I can do that.  Currently I'm getting acquainted with rspec.  Because of your PR I decided to add puppet-rspec tests for the next release. I'm going to get this done today or tomorrow. It's better in the long end to have tests.  As from time to time I get some fixes or new features.

**Comment by rgevaert** [comment]
I pushed a new release to the forge, not with the tests yet.  But if you want you can follow my test branch :).
